### ISSUE TITLE
Exposing utils to a styled component

### ISSUE THREAD

**Issue by allforabit** [modulz/stitches#101]
I'm just wondering if there's a good approach to exposing the utils in the styled component or if this is even a good idea?? Here's what I've came up with:

```ts
import * as React from "react";
import { styled, css, utils } from "../css";
import { PolymorphicComponent } from "react-polymorphic-box";

type ViewProps = Parameters<typeof css>[0];

export const View: PolymorphicComponent<ViewProps, "div"> = styled(
  ({ as, ...props }) => {
    const [cssProps, restProps] = React.useMemo(() => {
      const keys = Object.keys(utils);
      return Object.keys(props).reduce(
        ([cssProps, restProps], k) => {
          const v = props[k];
          if (keys.includes(k)) {
            return [{ ...cssProps, [k]: v }, restProps];
          } else {
            return [cssProps, { ...restProps, [k]: v }];
          }
        },
        [{}, {}]
      );
    }, [props]);

    const viewCss = React.useMemo(() => {
      return css(cssProps);
    }, [cssProps]);

    return <styled.Box {...restProps} className={viewCss} as={as || "div"} />;
  }
);
```
My other components will compose this base component and so will also have access to the utilities (which are driven by the tailwind utils). I think it would be nice to have it exposed like this for initial prototyping, etc and gives a similar workflow to using tailwind.

The component is consumed as follows:
```ts
export const MyComp = () => {
  return (
      <View mb={4} pt={2}>
          Some content here...
      </View>  
  );
};
```

**Comment by peduarte** [comment]
It could definitely be done, but I'm not sure it aligns with the objective of this library. I'm open to the idea, but would like to wait till after its officially launched and get some feedback.

I think Styled System mainly popularised this pattern, but since that wasn't built with Typescript, some issues weren't apparent.

I've used this approach a lot for long periods, and I do agree that overall it's a nice experience. 

However, IMO, it's only a pleasant experience to an extent:
- add margin, padding and background colour
- when you have very few props 

Then, it has quite a few drawbacks:
- prop clashes with valid HTML Attributes
- responsive styles were too distributed
- individual components only expose specific props
- extending component required extra TS typings

I think unifying all the utils in a single `css` prop is a really good approach. Every Stitches component supports it, so its something you learn once. It supports all CSS Properties, media queries, responsive values and token-aware values. It's fully types and has no clashes between variants/props with HTML Attributes.

**Comment by allforabit** [comment]
Thanks for getting back to me so quickly @peduarte. Yes I think it's best to wait until the initial release to see how it would fit in. And yep there's quite a few drawbacks to just passing in top level props and it can easily get out of hand when there's too many. The approach of using a single prop does seem to be the better option. 

Just one question, do you think it will be possible to support passing a plain object to the css prop? E.g.
```
<MyStyledComp css={{margin: 1}} />
```
I think this would be just as convenient as passing top level props. 

Thanks!

**Comment by peduarte** [comment]
Yep that would work too 👌
