### ISSUE TITLE
Is stitches still under maintenance??

### ISSUE THREAD

**Issue by yuval-shimoni-hunters** [modulz/stitches#1026]
I want to use `stitches` and want to make sure that stitches are still under maintenance & process...

**Comment by cpakken** [comment]
After @peduarte left the modulz, stitches and radix have been given much less attention. He was a really great communicator for the project and did a fantastic job in responding to issues + community outreach. Since he left, it feels like stitches and radix has been forgotten and left on the backburner.

I think that stitches and radix are beautifully designed and the best libraries in the react ecosystem, and I personally feel that it does them a huge disservice for these libraries to be left in such a state. Hopefully, someone can take on the role that @peduarte left and revitalize these two projects.

**Comment by jjenzz** [comment]
@cpakken if you are referring to the Radix Primitives, they were built by @benoitgrelard, @andy-hook and myself.

I have since left but they are still working hard on them so the primitives are very much alive. You only need to check the repo and you will see frequent progress. 

i cannot help re:stitches tho.

**Comment by yuval-shimoni-hunters** [comment]
@cpakken @jjenzz thanks you all. 
I also felt that stitches have a huge potential and it's really disappointing to hear that stitches aren't under signify development...

@LexSwed I saw that reference about CSS-in-JS..
But it's so weird there are so many projects that rely on CSS-in-JS, especially with `styled-components`
<img width="474" alt="image" src="https://user-images.githubusercontent.com/105345739/170243406-b5ee0def-836e-49a0-b617-f7f0db8356d5.png">

Do you really think that is something that will disappear from React eco-system??

**Comment by colmtuite** [comment]
I don't think that's a fair comment @cpakken. It's fair with regard to Stitches, it hasn't been getting much attention over the past few months. But @benoitgrelard and @andy-hook are working full-time on Radi, the repo activity is the healthiest it's ever been, and they both help out in Discord frequently. We're working towards a v1 launch soon.

**Comment by cpakken** [comment]
@jjenzz @colmtuite 

Thanks for clarifying the status of Radix primitives. I'm very glad to hear that the project is actively being worked on. 

As a fan of the project, I check https://www.radix-ui.com/docs/primitives/overview/release from time to time and my misunderstanding regarding Radix was because I noticed there were no new releases since the end of February. I thought this coincided with the lack of activity in stitches and drew connections where there were not. 

Sorry :sweat:

**Comment by benoitgrelard** [comment]
You can follow the milestones progress here too: https://github.com/radix-ui/primitives/milestones

**Comment by colmtuite** [comment]
No prob at all @cpakken. Easy mistake to make. All the ❤️

**Comment by yuvalshim** [comment]
> You can follow the milestones progress here too: https://github.com/radix-ui/primitives/milestones.
> 
> You can even take a peek at all the documentation changes (including the release notes) for the upcoming changes so far:
> - https://github.com/radix-ui/website/pull/368
> - https://radix-website-git-release.modulz-deploys.com/

So do you recommend us to pick stitches for our project? 

I didn't see topics that related to stitches there...

**Comment by colmtuite** [comment]
The React team recommend people use static CSS solutions rather than runtime CSS-in-JS solutions. Here is a [GH discussion](https://github.com/reactwg/react-18/discussions/110). More info in this [Twitter thread](https://twitter.com/sebmarkbage/status/1529622371333709825).

Stitches is a runtime lib, so it's not currently a lib that the React team would recommend. Furthermore, Stitches is not compatible with React 18's streaming feature. If you don't plan to use streaming, then we consider Stitches v1 stable, and it should work fine for your project. If on the other hand, you want to "future-proof" your project, and remain aligned with the general direction of the industry, you might want to consider a static solution instead.

We have explored a static version of Stitches, which uses the same API, but we have not yet committed to completing and shipping it.

**Comment by cpakken** [comment]
@colmtuite With your thoughts on static css being more future-proof, is modulz.app still using stitches to style its UI? If not what is your team using?

**Comment by colmtuite** [comment]
@cpakken Yes all of our apps (including Radix docs/site, Stitches docs/site, Modulz app, Modulz site, admin apps etc.) use [our design system](https://github.com/radix-ui/design-system), which is built on Stitches v1.

That's not too relevant though imo. My point above is that the React team (and the broader front-end community too imo) is not in favour of runtime styling solutions. The general direction things are headed is towards styling solutions that don't have any runtime cost. So if you want to make a "future-proof" decision, that is the data point to track. What any one company is currently doing is almost irrelevant.

**Comment by fabien-ml** [comment]
Please don't forget that stitches is not only about React. Its bad for people using `@stitches/core` to be collateral damage of React team "decision".

**Comment by mrhoodz** [comment]
Stitches is really thoughtfully designed I hope the project survives
