### ISSUE TITLE
Numeric tokens and math

### ISSUE THREAD

**Issue by mattfelten** [modulz/stitches#168]
I'm trying to use numeric token values with some light math and I'm not figuring out if there's a syntax that will work with this. I've tried subtracting the values and also using CSS' `calc`, both with no luck.

```
space: {
	$0: '0',
	$1: '8',
	$2: '16',
	$half: '4',
}
```

```
const Component = styled('div', {
	padding: ('$2' - '$half') '$2',
}
```

Any ideas?

**Comment by peduarte** [comment]
We will eventually support parsing tokens in the CSS `calc` function

Tokens get converted to CSS variables, but special characters are removed (because you cant use them in CSS variables)

So, you can always rely on those, as a temp solution:
```
const Component = styled('div', {
  padding: 'calc(var(--space-2) - var(--space-half) var(--space-2))',
}
```

Wanna give it a try and let me know if that works for you? I'll keep this issue open until we support parsing tokens in calc and the ability to run maths operations

**Comment by mattfelten** [comment]
That work, thanks!

In this example, it look like the second part of the `padding` shorthand prop still works as a token also. It's just the calc/math part that has to be written as a css variable.
```
padding: 'calc(…) $2'
```

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
