### ISSUE TITLE
Sometimes spreading the  props to the styled component doesnt work

### ISSUE THREAD

**Issue by denniscual** [modulz/stitches#178]
# Bug report

## Describe the bug

When wrapping a Styled component, like creating an `IconButton`, then spreading the rest props to it sometimes doesn't work or it creates a very weird behaviour which is odd. The weird behaviuor is that the it doesn't follow the styles based on the current variant props value.

The solution for this is to exclude the variant prop to the rest props then manually passing it to the styled component. 

Here is the screenshot which create a bug on my end. `RootIconButton` is a styled component created by stitches.
![image](https://user-images.githubusercontent.com/17754712/92276007-c7e7b880-ef22-11ea-8d48-565fbacd53a3.png)

And this is the solution I found
![image](https://user-images.githubusercontent.com/17754712/92276086-ebaafe80-ef22-11ea-8252-bb71840de132.png)

The difference is that the latter image shows a manual passing of `appearance` prop to the `RootIconButton`. With this, it returns the right output.

**Comment by peduarte** [comment]
Huh? 🤔 That's odd 😂 

Can you please share a minimal reproducible example, please?

We'll look into it asap.

Thanks!

**Comment by denniscual** [comment]
Yeah its odd. Here you go I prepared a codesandbox and put some comments - https://codesandbox.io/s/vibrant-shape-oti2i?file=/src/components/IconButton.tsx . Im not sure why it behaves like this. 

In terms of environment on my end, I used CRA and basically the codesandbox and it shows the same buggy result.

**Comment by peduarte** [comment]
@denniscual Thanks for this!

I think the issue is with the way the `compoundVariant` is setup. The children are indeed being rendered, but the text color is set to the same as the background color.

If you compare the rendering of the `IconButton` and the `Button` in `App.tsx`, you'll see that the `IconButton` also sets `appearance="outlined"` variant.

Then if you check the Compound variant [here](https://codesandbox.io/s/wizardly-germain-9q25n?file=/src/components/Button.tsx:2661-2684) you'll see the `color` property is set to `$primary`

So yeah, maybe try going through the compound variant rules and let me know how you get on 👍 

[Here's a fork](https://codesandbox.io/s/wizardly-germain-9q25n?file=/src/App.tsx) of your CodeSandbox without `appearance="outlined"`

![CleanShot 2020-09-04 at 22 23 45@2x](https://user-images.githubusercontent.com/372831/92282110-51848f80-eefd-11ea-908c-970b6e1aec95.jpg)

**Comment by denniscual** [comment]
@peduarte thanks for the reply! I checked again the codes and I've been thinking the variants configuration is correct. Yes on my sample I want to make the icon buttons to `outlined` but it doesn't work well. When setting it to `outlined`, the `backgroundColor` was filled but I assume that the `backgroundColor` is transparent because I set that css under the `outlined` variant. Adding the `backgroundColor` to transparent inside the compound variant did the job. But I assume I don't need to do it because I already override it. Basically about setting this up [I just followed the codes from the stitches](https://stitches.dev/docs/variants#compound-variants) about `compoundVariant` and you can see it that the `color` and `outlined` setup is almost the same.

**Comment by peduarte** [comment]
> Adding the backgroundColor to transparent inside the compound variant did the job.

Yep, that's exactly it 💯 

It's what the demo does too:

![image](https://user-images.githubusercontent.com/372831/92303234-32c0e000-ef73-11ea-869a-a8ce5f6536dd.jpeg)

Glad you solved it! Let me know if you have more questions.
