### ISSUE TITLE
Cannot apply themes correctly in a Next.js app.

### ISSUE THREAD

**Issue by steveruizok** [modulz/stitches#180]
# Bug report

## Describe the bug

In stitches, colors are defined as global variables on the document root. Themes are classes that override these global variables in the branch of the DOM tree where the class is applied. Therefore, to make a theme apply "globally", you would want to apply the theme's class at very root-most element of the tree, most likely the document's `<body>` tag.

In a Next.js app, the root of your document (including your `<body>` tag) is defined in the app's "document" file. You can create a [custom document](https://nextjs.org/docs/advanced-features/custom-document) file, `_document.js`, however because this file is server rendered, it cannot respond to the state of your app. 

As a result, **in a Next.js app, if you want a user to be able to change the theme through some state, you must apply your theme "down tree" of the `<body>` tag**. In some cases, this can result in unusual styles. (For example, when overscrolling a page like [this one](https://codesandbox.io/s/async-sound-b2012?file=/src/styles.css)).

## To Reproduce

1. Create a Next.js app with stitches.
2. Create themes.
3. Apply the theme statefully at the highest level possible (an element, child of `<body>`, in the `_app.js`).

## Expected behavior

One of the things I like about stitches is its lack of runtime javascript activity. In this case, however, we might want to break that rule and give a developer the ability to apply a theme to the document's root styles. In my case, I've done this with an effect:

```jsx
useLayoutEffect(() => {
    const root = document.documentElement

    for (let key in theme.definition) {
      const prop = '--colors-' + key.slice(1)
      const value = theme.definition[key]
      root.style.setProperty(prop, value)
    }
}, [theme])
```

...but perhaps there's a better way!

**Comment by peduarte** [comment]
This is excellent, thanks for putting this together 👍 

In the Stitches site, we used [use-dark-mode](https://github.com/donavon/use-dark-mode/) hook, which handles adding the classname to the `body` for us. 

This is [how we did it](https://github.com/modulz/stitches-site/blob/master/pages/_app.tsx#L16-L19). Internally, `use-dark-mode` toggles the provided body class when needed. 

Do you think there's something from within Stitches that can be done to solve this? It seems to be like an implementation limitation with Next.js.

As you've seen, the way theming works in Stitches is super simple, since it relies on CSS variables, so we cant make any type of assumption that your theme class will be added to the `body`. There are many websites that mix light and dark themes within the same page, etc.

Open to ideas 💡

**Comment by steveruizok** [comment]
Oof, I may have drilled so far into setting the class in JSX that I forgot that we can toggle classes imperatively. This works fine!

```
  useEffect(() => {
    document.body.className = theme
  }, [theme])
```

I'd consider adding something like this to the vercel example. I agree that having mixed themes can be really useful, and I like the approach!

**Comment by peduarte** [comment]
@steveruizok awesome stuff. I'll add that to the next example. Cheers for raising an issue!
