### ISSUE TITLE
Compound variant styles get applied to Base component

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#228]
# Bug report

As reported on [discord](https://discord.com/channels/752614004387610674/752795957674115092/756212104528396368)

## Describe the bug

When I apply `:hover, :focus` etc. style inside `compoundVariant` function of a component
- It isn't restricted to only that instance of the component
- It bleeds out to other component instances that do not have the compound variant combination 
- It also gets applied to the Base component/tag itself.

I tried using `:hover`, `&:hover`, `[${componentName}:hover]` - there's a slight difference in behaviour but it's not exactly the correct behaviour

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://codesandbox.io/s/stitches-ts-issue-forked-9xh5h?file=/src/App.tsx
2. Hover over the boxes

**Comment by afzalsayed96** [comment]
Possibly related to #216

**Comment by hadihallak** [comment]
Hey @afzalsayed96 
thanks for reporting this issue 🙏 

I looked into the issue and this behaviour is not related to compound variants but to the lack of comma separated rules support in Stitches currently 

For now and until this issue is resolved you will need to separate the comma separated rules like in the codesandbox below
https://codesandbox.io/s/stitches-ts-issue-forked-2m8tw?file=/src/App.tsx

will be closing this issue now as this is already reported in #233 but feel free to re-open it if i'm misunderstanding anything.

**Comment by afzalsayed96** [comment]
@hadihallak Can confirm this was indeed the issue. Thanks for the response
