### ISSUE TITLE
Stitches do not work with React libraries that expect className to be a string

### ISSUE THREAD

**Issue by SogoCZE** [modulz/stitches#229]
# Bug report

## Describe the bug

Stitches do not work correctly with some libraries that work with `className` prop because they expecting `className` prop to be a `string` but in Stitches, it's `object` with atoms and `toString` method.

And some libraries and even technologies (stencil.js - https://github.com/modulz/stitches/issues/191) work with className in the following way:

```javascript
className.split(' ')
```
- [React Font Awesome codebase](https://github.com/FortAwesome/react-fontawesome/blob/master/src/components/FontAwesomeIcon.js#L16)
- [StencilJS codebase](https://github.com/ionic-team/ionic-framework/blob/master/packages/react/src/components/utils/attachProps.ts#L40)

but this gives us an error because `split()` is not a method on an object that Stitches passes to the `className` prop. One solution to this problem would be to use `toString()` method and then use `split()` like this:

```javascript
className.toString().split(' ')
```
but this solution requires to change a lot of libraries and technologies out there. So it's not ideal.

## To Reproduce

[CodeSandbox with specific error](https://codesandbox.io/s/stitches-font-awesome-2nkx7?file=/src/App.tsx)

## Expected behaviour

Stitches will correctly work with libraries like [React Font Awesome](https://github.com/FortAwesome/react-fontawesome).

## System information

- OS: Windows
- Browser: any

**Comment by peduarte** [comment]
Thanks for this 💯

**Comment by Beingbook** [comment]
I'm dying for this. For faster release, what can I contribute?

**Comment by LexSwed** [comment]
hey @Beingbook 
One suggestion for you would be to use [`react-icons/fa`](https://react-icons.github.io/react-icons/icons?name=fa) and use polymorphic `as` prop on a styled component: https://codesandbox.io/s/stitches-font-awesome-forked-ryrvy?file=/src/App.tsx

**Comment by peduarte** [comment]
@Beingbook sorry for the delay. We're about to finalise the 0.1 release, which is a complete re-write. Most of the issuses will be solved as a result, so we're not actively patching up things in the current codebase.

The new version will be ready in only a few weeks!

**Comment by LexSwed** [comment]
@peduarte anything we can help with to speed up the release? 👀

**Comment by peduarte** [comment]
@LexSwed not currently, but once its ready we'll do a candidate release, then we'll need as much help as we can testing it 🙏

**Comment by jonathantneal** [comment]
@LexSwed, and your enthusiasm is very encouraging during this last stretch of work. 🙏

**Comment by vincerubinetti** [comment]
I think the fix here only works with the `styled()` function for creating components. The `css()` function still always returns an object that can't be interpreted correctly by Font Awesome and other libraries (it'd be great to have an param in the css function to just get the class name maybe).

I have a generic `Icon` component and I wanted to apply styles to a specific instance of it, and here's how I had to do it:

```tsx
// Footer.tsx
const iconStyle = css({
  fontSize: "1.2rem",
});

const Footer = () => (
  <footer>
    <Icon className={iconStyle().toString()} icon="github" />
  </footer>
);

// Icon.tsx
type Props = {
  icon: IconName;
  className?: string;
} & HTMLAttributes<SVGElement>;

const Icon = ({ icon, ...props }: Props) => {
  const match = findIcon(icon); // lookup icon by name in any of the styles (brands, regular, solid, etc)
  if (match) return <FontAwesomeIcon icon={match} {...props} />;
  else return <></>;
};
```

Note the `iconStyle().toString()`, and `className: string` definition. And unfortunately `className={iconStyle()}` doesn't throw a typescript error because the return type from `css()` is apparently a union of `string` and `{ className: string, ...etc }`, even though it seems to always return an object??

Related: https://github.com/stitchesjs/stitches/issues/928

> css()
> A function to generate class names from a style object.

Misleading and needs explanation/clarification.
