### ISSUE TITLE
Improve typing of `createStyled`

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#234]
We need to ensure that only expected keys can be passed to `createStyled` (and `createTokens`)

From @andykenward:

I've been looking at the source code for stitches and i think it might the usage of TypeScript generics on some of the functions.
e.g
```
export const createTokens = <T extends ITokensDefinition>(tokens: T) => {
  return tokens;
};
```

```
export const createStyled = <Config extends TConfig>(
  config: Config
):
```

These will only error if there arent any keys in the object that are defined in the interface.

So for createTokens

```
const tokens = createTokens({
      bob: {},
      colors: {
        RED: 'tomato',
      },
    });
```
is allowed

But if you dont havecolors or any known interface key from ITokensDefinitions then it will error.
for example

```
const tokens = createTokens({
      bob: {},
      colsors: {
        RED: 'tomato',
      },
    });
```

or
```
const tokens = createTokens({
      bob: {},
    });
```

Will both error.

**Comment by hadihallak** [comment]
Spent a lot of time on this and tried a lot of different ways but couldn't get it to work given our use case
right now, the only way I could see this supported is if typescript allowed us to type unknown properties in an object to a type that doesn't intersect with known ones which I think I've seen people discuss previously in one of the issues in typescript so this might eventually be possible.

I'm leaving this minimum repo codesandobx for people to test against so that maybe someone is able to achieve what we're looking for https://codesandbox.io/s/relaxed-noether-ke6ui?file=/src/App.tsx
