### ISSUE TITLE
global style on next.js not being applied

### ISSUE THREAD

**Issue by vitordino** [modulz/stitches#296]
# Bug report

## Describe the bug

Hey there, first time user here 👋  (although an avid follower from the start)

I just tried creating a `GlobalStyles` component on a next.js app, but no matter what i put it there (`body`, `html`, `.someGlobalClass`) it doesn’t seem to be applied.

am i doing something wrong?

## To Reproduce

Either see this [codesandbox example](https://codesandbox.io/s/stitches-global-nextjs-bug-rsf9x) or:

1. Follow the [Using Next.js with Stitches post](https://stitches.dev/blog/using-nextjs-with-stitches)
2. Add a `css.global` call
3. See error

## Expected behavior

Global styles should be applied on Next.js apps

## Screenshots

<img width="1464" alt="Screen Shot 2020-10-26 at 4 34 15 AM" src="https://user-images.githubusercontent.com/5063967/97145199-93cf8d80-1744-11eb-8ed9-9541f8feb7dd.png">

## System information

- OS: `macOS` and `codesandbox`
- Version of stitches: tested stable `0.0.2` and `0.0.3-canary.4`
- Version of Next.js: `9.5.3`
- Version of Node.js: `12.16.3`

**Comment by peduarte** [comment]
Thanks for raising this.

The `css.global` API changed a little since `0.0.2` (which is the documented version right now)

`css.global` now returns a function that needs to be invoked within your top level component. 

I see you're trying to wrap it in a Component. We're also considering that API for the react layer. There's a discussion about this here: https://github.com/modulz/stitches/discussions/285

The Sandbox you linked is not starting for me, probably an issue on their side. But can you try returning `css.global` instead of returning `null`?

If that doesn't work, then I suggest:
```jsx
const globalStyled = css.global({ ...styles })

const App = () => {
  globalStyles();

  return <div />
}
```

**Comment by vitordino** [comment]
wow, amazing response time 😱 

yep, that definitely did the trick ✨

if you need any help writing docs for the next version, just ping me here ✌️

**Comment by peduarte** [comment]
@vitordino awesome, thanks so much
