### ISSUE TITLE
Is there an API to access the tokens defined in the initial theme?

### ISSUE THREAD

**Issue by colshacol** [modulz/stitches#308]
Using css.theme you can access theme definitions.

```js
const darkTheme = css.theme({
  colors: {
    $foo: '#000'
  }
})

console.log(darkTheme)
// Output: { definition: { colors: $foo: '#000' } }
```

Is there a way to access the definitions provided to `createStyled`?

**Comment by colshacol** [comment]
I realize how easy it would be to just externalize the definitions like so:

```js
const tokens = {
  colors: {
    $foo: '#00',
  },
  // ...etc
}

const { style, css } = createStyled({
  tokens
})

// access initial definitions...
tokens.colors.$foo
```

-- I'm just curious if the API exists to access the values inside of `styled` or `css`.

**Comment by peduarte** [comment]
@colshacol hey! Not currently. Our approach so far has been to abstract the tokens in its own object, and share it that way (as you also suggested)

Do you think that it would be good for us to offer a first class API for this? If so, how do you see it?

**Comment by colshacol** [comment]
@peduarte No, if you don't already offer it, I don't think you should.

It took me a few weeks of fist-fighting this tool before I finally realized **what it is and what it is not.**, but lately I have grown to really appreciate how Stitches works. -- I think a definitions introspection API is unnecessary, would stray from what seems to be "the Stitches way", and just be bloat when somebody could just extract their tokens. :)

**Comment by JoshRosenstein** [comment]
I was looking for something similar, but having the map to the css variable, rather than the actual token value.
Similar to [dash-ui](https://github.com/dash-ui/styles/blob/2fe6bcbf1a74cef66fdad6520abbfc21a50086d6/src/create-styles.ts#L218)
I ended up creating a function that mimics [stiches token var formatting](https://github.com/modulz/stitches/blob/818398bd6eac847de4f08d479046fda361d4c819/packages/core/src/index.ts#L590) , I then run my initial theme through this function and export it in order to just use it [for Calc functions](https://github.com/modulz/stitches/issues/244) etc.

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
