### ISSUE TITLE
renderToString not working

### ISSUE THREAD

**Issue by yovanoc** [modulz/stitches#311]
# Bug report

## Describe the bug

We try to use stitches to render our mail with the renderToString() method from react-dom/server and the styles are not included we don't know why :/

## To Reproduce

call with `renderToString(<Base title="TITLE" />)`

## Expected behavior

styles included in the final html

## Screenshots

<img width="547" alt="image" src="https://user-images.githubusercontent.com/7302317/99065347-8ec56780-25a7-11eb-916f-ad5fdc705a91.png">

<img width="970" alt="image" src="https://user-images.githubusercontent.com/7302317/99065374-97b63900-25a7-11eb-901f-9a2cdd09050c.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/7302317/99065399-a1d83780-25a7-11eb-801d-b78c1fc25d58.png">

**Comment by hadihallak** [comment]
Hey @yovanoc 👋 

I think you're using the SSR functionality incorrectly, 
the `css.getStyles` function accepts the final app you're going to render.
It's important that it renders the app in order for it to be able to collect the styles.

Right now you're only passing it an empty function, hence it's not able to collect any styles

so here is a way to fix this:
1. encapsulate everything that uses stitches styles in one react component `App.tsx`
2. inside your `Base` component that renders the final HTML, you should not use any stitches components there. you then will be able to call 
```tsx
// here the result will be the output of running <YourApp/> 
const { result, styles } = css.getStyles(() => <YourApp/>);
```
3. use `styles` and `result` to construct the HTML in your Base component.

I believe that this should fix your issue so I'm gonna close it but If you're still having the issue after doing the above, then please feel free to re-open it with a code reproduction that we can run (codesandbox, github repo, etc..) and we will be happy to assist you further ❤️

**Comment by yovanoc** [comment]
Thanks for these informations but I not sure to understand. Here's what I changed and it gives me the exact same result:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/7302317/99144237-9434b780-2664-11eb-8aa6-db73c96c126f.png">

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/7302317/99144244-a3b40080-2664-11eb-967f-e5317b2e051b.png">

**Comment by hadihallak** [comment]
@yovanoc 
here is a working nodejs based codesandbox with `renderToString` working correctly https://codesandbox.io/s/crazy-bhabha-r4u9x?file=/src/index.js
one thing that I forgot to mention in my last comment is that the `renderToString` call needs to happen inside the callback for the styles to be injected correctly

besides that, in your screenshot, the global styles call will also need to happen inside the getStyles callback.
the result will be the HTML string so you will likely need to use dangerouslySetInnerHTML on the body.

if you apply the above changes and things are still not working for you. it would be very helpful if you could provide a repo or a codesandbox so that we could assist you better.

**Comment by yovanoc** [comment]
Thanks. All is working perfectly now!
