### ISSUE TITLE
[0.1.0-canary.x] Pass variants as props to wrapped components

### ISSUE THREAD

**Issue by cappuc** [modulz/stitches#416]
# Bug report

## Describe the bug

When extending a stitches styled components variants styles of parent and child are merged but when extending a wrapped component only the style of the child is applied because the variant prop is not passed down to the component and the default value is applied.

## To Reproduce

[codesandbox example](https://codesandbox.io/s/stitches-pass-variants-down-to-wrapped-component-9fz2m)

## Expected behavior

I don't know if this is something you want to support or not but it can be useful.

**Comment by jonathantneal** [comment]
Your example has 4 components, which I’ll refer to as _**Box_A**_, _**Box_B**_, _**Gen_Y**_, and _**Box_Z**_.

- _**Box_A**_ has a variant (_with a key/value pair of `color`/`red`_).
- _**Box_B**_ extends _**Box_A**_, and it also extends the same variant.
- _**Gen_Y**_ is a generic component, not a stitches component, and it does not extend anything, but it wraps _**Box_B**_, and it introduces a variant with the same key/value pair.
- _**Box_Z**_ extends _**Gen_Y**_, and it also extends the same variant.
- All components are activating the same variant.

Therefore:

- _**Box_B**_ will activate the variant of _**Box_B**_  and _**Box_A**_ before disposing the prop.
- _**Gen_Y**_ will activate the variant of _**Gen_Y**_,  and also _**Box_B**_ and _**Box_A**_ before disposing the variant prop, because _**Gen_Y**_ is a generic component that does not contain any logic for disposing the variant prop.
- _**Box_Z**_ is a stitches component which will dispose of the variant before activating _**Gen_Y**_, meaning that neither _**Gen_Y**_, _**Box B**_, or _**Box_A**_ will receive the variant prop.

I’ve verified this functionality in #450, tho it might already work.

I’m sorry for the late reply. It required a great deal of concentration to remember what should work when. It makes for a very interesting mix. 😅
