### ISSUE TITLE
Specificity issue when components share the same style

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#474]
Repro: https://codesandbox.io/s/identical-styles-specificity-issue-forked-qijm7?file=/src/App.tsx

**Comment by acconway** [comment]
Upon looking at this more, I wasn't accurate labeling it as `specificity`, the core issue here is the duplicate class definitions. 

This is becoming a more critical issue in our app, not because we're re-using styles among multiple components, but because this is also happening when we're lazy loading. When a section loads async, it adds only the stitches classes needed for the component instances contained within it, which results in an uneven duplication of classes and some funky behavior. 

Ex:

App 1 includes a "<Button>" with "size: normal" and "style: primary" variants
App 2 includes a "<Button>" with "size: normal" and "style: secondary" variants

App 1 loads first, then App 2, in different sections of the page so both are visible at once. Stitches CSS ends up with class definitions like

```
.<Button>

.<Button-size-normal>

.<Button-style-primary>

.<Button>

.<Button size-normal>

.<Button style-secondary>
```

So the "primary" button has the base <Button> styles applied **after** primary variant, which messes up the display

**Comment by acconway** [comment]
@peduarte So the sandbox I originally posted is no longer reproducible on `v0.1.0-canary.20`, because of https://github.com/modulz/stitches/pull/485/files, but that hasn't solved the root issue. 

Here's another sandbox which demonstrates the problem more clearly https://codesandbox.io/live/1d1t7h0?file=/src/App.js

Notice that the border of `<Button2>` changes from blue to red on click (because a new, duplicate class is inserted after `<Button2>`'s class).

https://github.com/modulz/stitches/pull/485/files fixes the first issue because it's avoiding a write to the style tag, which includes the duplicate class definitions, but the root cause (that when `update` is called the `unitedCss` includes duplicates) is not addressed. So as soon as a "new" rule is added and `update` is called, the duplicates will be written.

You can see a downside of the approach in 485 play out in the sandbox I linked here if you change the order of components.

In this case,`<Button3>` styles are added first, they aren't unique so in `insertMethod` the write is skipped. Then, `Wrapper` is added, now we have a unique new style, and the write with the duplicate happens.
```
      { showThing && <div><Button3>button3</Button3><Wrapper>NewComponent</Wrapper></div>}
```
If you reverse the order, the issue is fixed 😄 ! Now `<Wrapper>` styles are added, write happens, then `<Button>` is added, write is skipped as there's nothing new. But we've just postponed the bug until a new style is added.
```
      { showThing && <div><Wrapper>NewComponent</Wrapper><Button3>button3</Button3></div>}
```

**Comment by acconway** [comment]
Actually, we overcomplicated the sandbox there, it's not even necessary to hold back the render so it happens asynchronously. It simply comes down to rendering order https://codesandbox.io/s/duplicate-classes-9y0fx?file=/src/App.js

**Comment by peduarte** [comment]
@acconway thanks for that

**Comment by hennessyevan** [comment]
Any news here or a workaround? We're being plagued by a similar bug. We have two apps on the same page (both using a stitches DS) loading both completely breaks the style tag output

**Comment by peduarte** [comment]
@hennessyevan not sure I follow. a minimal reproducible example would help. sounds like in your case the [insertion method](https://stitches.dev/docs/api#insertionmethod) API might help.

**Comment by hennessyevan** [comment]
Thanks @peduarte. The issue I was happening actually isn't with stitches at all but with our webpack setup. That was a frustrating revelation. Sorry for polluting this issue.

**Comment by peduarte** [comment]
Validated: https://codesandbox.io/s/identical-styles-specificity-issue-forked-uvd54?file=/src/App.tsx

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you
