### ISSUE TITLE
Review syntax in object styles

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#52]
Currently to target a descendant you need to:
```
{
  " svg": {}
}

```

I think adding a space before the selector isn’t very intuitive. Shall we keep it inline with other object style syntaxes?

So, a nested key can be a descendant or a pseudo class. Pseudo classes start with a colon.

We should allow nesting as many levels as possible too. 

For example:

```
{
  ":hover": {
    "svg": {}
  }
}
```

Is the equivalent of: `component:hover svg`

The need to nest becomes even more appealing when targeting other instances of Styled Components:

```jsx
{
  [`${Component}:hover`]: {}
}
```

I think the general DX would be better like this:
```jsx
{
  [Component]: {
    :hover: {}
  }
}
```

Hope this makes sense. On my phone 😆

**Comment by jjenzz** [comment]
Just going to add the ampersand to the conversation here too 😛 

Currently, if we need to style a component based on the state of another, it seems we have to do something like this:

```jsx
const Checkbox = () => (
  <CheckboxPart>
    <Input />
    <FakeInput />
  </CheckboxPart>
);

const CheckboxPart = styled('div', {});

const Input = styled('input', {
  ":checked + .my-fake-input-class": {
    color: 'green',
  }
});

const FakeInput = () => <FakeInputPart className="my-fake-input-class" />

const FakeInputPart = styled('div', {
  color: 'black',
});
```

I struggle with this architecturally because we need to scan the entire file to reason about the styles of the `FakeInputPart`. To solve this I usually keep all styles for a component within their component declaration as follows:

```jsx
const Checkbox = () => (
  <CheckboxPart>
    <Input />
    <FakeInput />
  </CheckboxPart>
);

const CheckboxPart = styled('div', {});
const Input = styled('input', {});
const FakeInput = styled('div', {
  color: 'black',

  [`${Input}:checked + &`]: {
    color: 'green',
  }
});
```

I'm curious to hear thoughts on whether stitches could support something that would allow for this encapsulation?
