### ISSUE TITLE
`border: none` 💥

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#58]
I've noticed that the following declaration:
```
border: 0
```

yield some unexpected results. (@christianalfoni  I think you came across that in yesterday's stream too)

I kinda understand _why_ this may happen, but think it's an unintuitive DX. 

Changing from `0` to `'0'` (String) partially solves the issue, but some of the border long-hands property are still being generated as `undefined`:

<img width="304" alt="CleanShot 2020-07-29 at 10 58 52@2x" src="https://user-images.githubusercontent.com/372831/88779959-a14b9a80-d18a-11ea-861d-2ee873629be6.png">

**Comment by hadihallak** [comment]
Just want to add that with the latest release this produces slightly different results so now single values are treated as [borderWidth](https://github.com/modulz/stitches/blob/3dc0bef929e95956757386e5c1cede55b0242ba6/packages/css/src/utils.ts#L126) so `border:0` works correctly, however, `border: "none"` will not as none isn't a valid border-width value.

I'm wondering if we should parse all shorthand values so that it matches CSS or if we should remove the shorthand syntax all together because I'm thinking if we support the shorthand syntax partially then this might be confusing to people unaware with what's going on [under the hood](https://github.com/modulz/stitches/blob/3dc0bef929e95956757386e5c1cede55b0242ba6/packages/css/src/utils.ts#L117).
