### ISSUE TITLE
Page-specific body styles

### ISSUE THREAD

**Issue by ymcheung** [modulz/stitches#597]
## Describe the bug
React 17.0.1
Next 10.2

I use `global` to define page-specific `<body>` styles and set up SSR according to https://stitches.dev/docs/server-side-rendering
The body styles used in `pages/index.tsx` will be also in <body> of `pages/about.tsx`.

What should I do to set page-specific body styles correctly?

Thank you!

## To Reproduce
https://codesandbox.io/s/sharp-goldstine-clpvi
1. Click the link to `About`
2. `Index`'s body styles are present in `About`
3. Click `Home`
4. `About`'s body styles are present in `Index`

## Expected behavior
Every page has their own <body> styles, not just overriding.

## Screenshots
![image](https://user-images.githubusercontent.com/4409977/117750535-26013400-b246-11eb-9b5f-86e32256f470.png)

## System information
- Brave Browser (Chrome DevTools 90)
- @stitches/react 0.1.9
- Node 14.16.1

**Comment by peduarte** [comment]
Interesting. The `global` function wasnt designed to support page-specific stuff. It's truly for global CSS. 

Right now, I think your options are:
1. Add a class to the body when your page changes, then use that class as a chained selector in your global CSS
```jsx
global({
  body: {
    '&.home': {},
    '&.about': {},
  },
})
```

2. Create a page-level component, which wraps each page, and add styles to that instead of body
```jsx
const Home = styled('div', {})
const About = styled('div', {})

function HomePage() {
  return <Home>...</Home>
} 

function AboutPage() {
  return <About>...</About>
} 
```

Would these work for you?
