### ISSUE TITLE
Latest Stitches does not work well with next-themes

### ISSUE THREAD

**Issue by janhoogeveen** [modulz/stitches#653]
# Bug report

I've noticed that recently my theme-switcher does not work (properly) anymore. The most noticeable changes to my project are an upgrade to Next 11 from 10 and an upgrade of Stitches from 0.1.9 to 0.2.x..

**1. Open the page. Notice that the resolvedTheme and theme value are set to `dark`, but the theme is `light`**

<img width="381" alt="image" src="https://user-images.githubusercontent.com/882219/122905854-df791c00-d351-11eb-97af-e12a51607c0c.png">

There's no className derived from the dark theme in the HTML.
<img width="493" alt="image" src="https://user-images.githubusercontent.com/882219/122906053-0a637000-d352-11eb-8297-0e0072895d0b.png">

**2. Click on the `dark` button. The dark theme will get applied.**

<img width="445" alt="image" src="https://user-images.githubusercontent.com/882219/122905972-f6b80980-d351-11eb-984c-e5ed0885d3f2.png">

Also notice that the className is now applied correctly. 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/882219/122906159-2535e480-d352-11eb-939d-6b141df5bde6.png">

## To Reproduce
I've made a reproduction on Codesandbox.
https://codesandbox.io/s/stitches-and-next-themes-os4vy

## Expected behavior

I'm suspecting the className does not get applied because it's undefined on first render? Totally not sure what's happening here, and it might very well be an issue with next-themes, but it was working before so that's why I'm raising the issue in this project first.

## System information

- OS: macOS
- Browser: FireFox
- Version of Stitches: 0.2.2
- Version of Node.js: Whatever Codesandbox uses

## Additional context

I've changed

```jsx
<ThemeProvider
  attribute="class"
     value={{
     light: "light",
    dark: darkTheme.className
  }}
>
```
to
```jsx
 <ThemeProvider
    attribute="class"
    value={{
      light: "light",
      dark: darkTheme
  }}
>
```
after upgrading Stitches.

**Comment by peduarte** [comment]
Removing `.className` is the correct thing to do 👍 

Im looking at your sandbox, but everything is working as expected.

What am I missing?

**Comment by peduarte** [comment]
We'll look into this, but for now, a workaround is to add `.toString` to the theme. Demo: https://codesandbox.io/s/stitches-and-next-themes-forked-6bp7p?file=/pages/_app.js:303-323

**Comment by janhoogeveen** [comment]
Adding `toString()` fixes things in our project too. Thanks a bunch! Really enjoying Stitches so far ✨ .

**Comment by peduarte** [comment]
@janhoogeveen thanks! we'll address this issue so adding `toString` is required. I'lll post an update here when its done and released.

**Comment by oeduardoal** [comment]
Hey @peduarte ! First of all, so fast is v0.2.2 :rocket: ... About this, I believe this should be listed in the breaking changes at  [site](https://stitches.dev/blog/stitches-0.2.0). We had some issues trying to use only theme instead of `theme.toString()` with storybook and our ThemeProvider... What do u think?

**Comment by peduarte** [comment]
In v1, doing `.className` should work!

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)

**Comment by jahirfiquitiva** [comment]
I am trying to do this and what I'm seeing is that the class attribute is not being set on first load if the theme is dark

<img width="323" alt="Shot 2022-01-02 at 22-21-18@2x" src="https://user-images.githubusercontent.com/10360816/147897617-344524ae-9c13-480d-9c26-df9a93b31bfd.png">

I am currently fixing it by doing
```typescript
useEffect(() => {
  if (!resolvedTheme) return;
  setTheme(resolvedTheme);
}, [resolvedTheme, setTheme]);
```

But the light theme is visible for a bit. I saw that @peduarte [CodeSandbox Demo](https://codesandbox.io/s/stitches-and-next-themes-forked-6bp7p?file=/pages/_app.js:303-323) returns null until the component is mounted, which I would like to avoid since it isn't needed by default with `next-themes` and simple css or emotion.

Any chance you can provide a better way to fix that? Thanks

**Comment by viniarruda** [comment]
Any suggestion?
