### ISSUE TITLE
Stitches throwing exceptions "TypeError - Converting circular structure to JSON"

### ISSUE THREAD

**Issue by tiagogm** [modulz/stitches#665]
# Bug report

## Describe the bug

I'm raising this bug here as requested on discord :)

Our team has been adopting stitches for a while and since release `0.2.0` we’ve started seeing exceptions in production that we can’t seem to replicate locally and we need some help

 Basically we started seeing loads of instances of:
  `TypeError - Converting circular structure to JSON. .. at JSON.stringify`
 
 The call stack lead us to stitches [createMemo](https://github.com/modulz/stitches/commit/3acc8adb8593d649231f17ec9833ddfd1f032a9a#diff-43e62b23b71688e3c16bac83ef32d4ae41faf750f6d094633688fdd76de70612R6) function.

## To Reproduce

Although we see a really high number of exceptions, we cannot seem to reproduce this :( 
We forked the code and added a bunch of logs to try to get as much info as possible, see below.

## Expected behavior

There should be no exceptions thrown

## Screenshots / Information

This a screenshot another user on [discord shared ](https://discord.com/channels/752614004387610674/752795957674115092/862571633965531166) about the same issue:

![Exception](https://media.discordapp.net/attachments/752795957674115092/862571631959605268/unknown.png?width=1080&height=540)

## System information

- OS: both
- Browser (if applies): It seems to occur in multiple browsers, safari, chrome and firefox (last 2 version) at least
- Version of Stitches: 0.2.2
- Version of Next.js: 9.x.x
- Version of React: 16.13

## Additional context

Since we could not replicate we forked the code to wrap that function in try catch, and the exceptions went away (we still got the error logs). 

We also logged the object value failing to get `stringified` and we got this shape:

```
{
  "prefix": "",
  "media": "[object Object]",
  "root": "[object HTMLDocument]",
  "theme": "[object Object]",
  "themeMap": "[object Object]",
  "utils": "[object Object]"
}
```

After adding a few more logs, we zoomed in in on the `root` object, which seems to point at times to [globalThis.document](https://github.com/modulz/stitches/blob/canary/packages/core/src/createCss.js#L28). 

In our case the document does in in fact have a circular reference (there is a form on the page with internal react object with circular references) . From what we gather from the logs we added, useMemo is stringifying an object of type HTMLDoc, which can in certain instances, contain circular references and throw exceptions.

We still can’t really replicate this issue locally, so any pointers or hints would be awesome

**Comment by peduarte** [comment]
Thanks so much for this. Sounds serious. We'll investigate!

**Comment by fatihcandev** [comment]
@peduarte I was getting this error while building my Next.js app but now it seems to be fixed after upgrading stitches to the latest version.

**Comment by peduarte** [comment]
Yeah I was hoping it would be 😄 Thanks!

Will close.

**Comment by rubenmoya** [comment]
Hello! We are having the same problem. We haven't touch the codebase in a couple of weeks but it stopped working suddenly.

We've updated to `1.0.0` but it's still broken. Any ideas?

**Comment by r00dY** [comment]
Please reopen, this error is still existing, in 1.0.0 and 1.1.0.

This bug happens when you stringify Window object (`JSON.stringify(window)`).

Really don't have time to do a PR, so let me quickly describe why this bug occurs:

`createStitches` function calls `createCreateThemeFunction` with input parameter `config` that has `root` property of type `HTMLDocument`. This `config` gets serialized with `JSON.strinfigy` inside. Some 3rd code can add anything to `globalThis.document`. Like an object with reference to a `window`. For example HotJar does that. And then it crashes.

LInk to problematic line of code: https://github.com/modulz/stitches/blob/52b781883b506b453cdb013fe098ed9176f3539b/packages/core/src/createStitches.js#L47

@peduarte do you need to serialize `config.root` at all? Didn't go that deep. Maybe that's a simple fix. Serialising entire `document` seems very dangerous and it definitely shouldn't be there.

**Comment by franklinjavier** [comment]
Here we're facing same issues 

**TypeError - Converting circular structure to JSON**

![image](https://user-images.githubusercontent.com/440220/132740272-86a7c349-05dd-4f82-b872-97cf982cd8fe.png)

**Hotjar**

![image](https://user-images.githubusercontent.com/440220/132740464-2d2ba789-8922-4b96-8511-2256eceb7d33.png)

**Comment by peduarte** [comment]
@franklinjavier Did you say `@stitches/react: 0.2.2`?

Would you mind upgrading to the stable version? The latest is `1.1.0`

Thanks!

**Comment by franklinjavier** [comment]
Yep. We are planning to upgrade, but @r00dY and @rubenmoya still getting the error.

**Comment by peduarte** [comment]
@franklinjavier Ruben's error was related to Google Maps API, and not to Stitches. He posted the following on the Discord server:


> Well, we found the problem
It just took 46 minutes :joy:
Since the error is related to circular structure in the document we started thinking what could be adding stuff to it. The only thing we came up with was the google maps API. We have a script tag in the _document with it, and it didn't have a pinned version. After changing it to an older one everything started working.

**Comment by r00dY** [comment]
I have this error too (with 1.0.0 and 1.1.0), described above why it occurs. In my case it's Hotjar. Stitches calls JSON.serialize on document but document can't be trusted not to have circulars.

**Comment by ethanresnick** [comment]
I tried this in 1.2.0 and I think it's still not fixed?

**Comment by peduarte** [comment]
Ok, re-opening.

**Comment by ethanresnick** [comment]
@peduarte @jonathantneal Any sense of what's involved in fixing this, and what the ETA is? Not trying to look the open-source gift horse in the mouth; I'm just curious so that I can prepare accordingly, as my project currently depends on a library (the Google Maps API) that creates one of these circular references, which makes it impossible to use stitches.

**Comment by peduarte** [comment]
@ethanresnick no ETA at the moment I'm afraid :( 

But some folks on Discord also narrowed it down to Google Maps API and have managed to work around it 

https://discord.com/channels/752614004387610674/885427118429835305/885430820087668736

![image](https://user-images.githubusercontent.com/372831/135845223-782936c8-13ec-4e12-9fa8-fe6d5d540a00.png)

**Comment by ethanresnick** [comment]
@peduarte Thanks! Very helpful to know about that workaround with the version pinning. That should be enough for our project right now

**Comment by peduarte** [comment]
Ok, Im gonna close this, as seems to be unrelated to Stitches specifically. If anybody else has this issue, please submit as a new issue with reproduction, etc. Thank you
