### ISSUE TITLE
Cannot use React.ComponentProps

### ISSUE THREAD

**Issue by graup** [modulz/stitches#669]
# Bug report

## Describe the bug

When you want to extend a styled component like this, you get type errors.

## To Reproduce

```ts
import { styled } from '@stitches/react';

const StyledButton = styled('button', {});

const Button = (props: React.ComponentProps<typeof StyledButton>) => {
  return <StyledButton {...props} />
}
```
```
Type 'InternalCSS<TMedias & { initial: ""; }, { colors: { blue: string; }; }, {}, CSSPropertiesToTokenScale> | undefined' is not assignable to type 'InterpolationWithTheme<any>'.
```

## System information

- Version of Stitches: 0.0.2
- Version of Typescript: 4.3.5

**Comment by graup** [comment]
Related discussion: https://github.com/modulz/stitches/discussions/213

This simple code not working seems like a bug to me, so I opened this as an issue.

**Comment by ruijdacd** [comment]
I've encountered this issue as well when first introducing stitches in our design system, and in our case the problem was being caused by Storybook, which internally uses `@emotion/core` for styling their interface.

The problem is that emotion is adding a type to all JSX and react components for their `css` prop, which then clashes with Stitches own `css` prop.
```ts
declare module 'react' {
  interface DOMAttributes<T> {
    css?: InterpolationWithTheme<any>
  }
}

declare global {
  namespace JSX {
    /**
     * Do we need to modify `LibraryManagedAttributes` too,
     * to make `className` props optional when `css` props is specified?
     */

    interface IntrinsicAttributes {
      css?: InterpolationWithTheme<any>
    }
  }
}
```

The workaround is to overwrite the types for the `@emotion/core` package on your `tsconfig.json` file, like so:
```json
{
  "compilerOptions": {
     // Other options
    "paths": {
      "@emotion/core": ["./typings/emotion.d.ts"]
    },
}
```

And then create the file to overwrite the types `typings/emotion.d.ts` with the following:
```ts
declare module "@emotion/core";
```

This solution might not be the best one, but it allowed us to enable the `css` prop on our components, without having to access internal types from Stitches.

**Comment by jonathantneal** [comment]
Based on discussion in https://github.com/modulz/stitches/discussions/213, this now seems to be working with `React.ComponentProps` in v1.0.0. Would anyone let us know if this is not the case?

**Comment by ekafyi** [comment]
Yes, everything works fine. Example on a fresh React + TS install: https://codesandbox.io/s/goofy-hooks-j9c31

**More specific details for future visitors searching this error**

If you use Storybook, it has Emotion as dependency that messes up the `styled` typing. The quick workaround is to modify the emotion type definition file like so: https://github.com/emotion-js/emotion/issues/1800#issuecomment-635288990

**Comment by hrasoa** [comment]
@jonathantneal as mentionned in #213 , the ```as``` prop is not passed from ```Reac.ComponentProps```.

**Comment by jonathantneal** [comment]
@hrasoa is correct. `React.ComponentProps` is now working, and this does not include the `as` prop. See https://github.com/modulz/stitches/discussions/213#discussioncomment-1301865
