### ISSUE TITLE
Add keyframe animation

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#68]
We need to support keyframe animation 🙌

**Comment by christianalfoni** [comment]
Suggest this is implemented as:

```ts
const animation = css.keyframe({
  '0%-50%': {
    // styles
  },
  '50%-100%': {
    // styles
  }
})
```

It can work exactly like the `css.theme`, meaning we introduce a new `KeyframeAtom` and this will be implemented exactly like the `css.theme` method, only it produces a keyframe rule instead of overriding css variables. Should also just create a sequenced name, or use hash when SSR.

**Note!** I do not believe theme uses hash when SSR now, that would need to be fixed as well 😄

**Comment by nathanielrindlaub** [comment]
Is this available in the current (0.0.2) release?

**Comment by peduarte** [comment]
@nathanielrindlaub Yep https://stitches.dev/docs/styling#keyframe-animations

**Comment by nathanielrindlaub** [comment]
Amazing - thank you!
