### ISSUE TITLE
Using stitches in a nextjs app will yield no styling if SSR is not setup.

### ISSUE THREAD

**Issue by hadihallak** [modulz/stitches#72]
Tested on a nextjs app with stitches/styled version 8.0.3

Not sure if this is intentional but I think that serverside rendering CSS should be optional and not a requirement 

**Expected behavior:** if no styles were sent from the server then they will need to be generated client-side

**Comment by peduarte** [comment]
This is an interesting one. Thanks for raising it!

**Comment by christianalfoni** [comment]
Hm, yeah, this is interesting indeed. Cause the way stitches goes into SSR mode is by looking for any style tags created, but those are not created, so should not be any difference. 

The only thing I can think of is that React does not actually do an additional render, maybe because Next.JS does some crazy stuff noticing the component is static or something. That means no injection can happen. 

But I am curious... is this more of an "expected behaviour" thing or do you actually not want to use SSR? If latter... why? 😄

**Comment by hadihallak** [comment]
yeah mostly an expected behavior as this is how it works in other libraries until you see FOUC then you notice you need to setup SSR 😄

**Comment by hadihallak** [comment]
fixed in #120
