### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#75]
We need to put in place a better release flow to avoid regressions.

Im not quite sure whats the best way to do this, but open to suggestions @christianalfoni and @hadihallak 

Ideally, Id like to have a test suite of all the things we know we need to support. Im happy to add the tests once the structure is in place

**Comment by christianalfoni** [comment]
What is missing is running React tests with JSDOM ideally, so that we can actually test the injection. So Jest is already set up, but need to add something like Enzyme I believe. Here is a tutorial: https://medium.com/@salihunuruddeen/how-to-configure-jestjs-unit-test-environment-for-test-in-react-js-7b8b6b9a2a0b

For the typing it is required to set up a different kind of test suite: https://www.simonholywell.com/post/testing-typescript-types.html. Never set up that before, but yeah, here is an example 😄
