### ISSUE TITLE
DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet' (file system based access)

### ISSUE THREAD

**Issue by sgrtho** [modulz/stitches#756]
# Bug report

## Describe the bug

Environments using local-style resources (think of `file://`) might fail initialization because in this context scripts lack permissions to access `.cssRules` of linked stylesheets.

The topic is covered here:

https://stackoverflow.com/questions/48753691/cannot-access-cssrules-from-local-css-file-in-chrome-64

## To Reproduce

Since this is primarily an *environment*-related (and probably rare) issue, I won't provide a working example. But I think it is obvious that the issue originates from...

https://github.com/modulz/stitches/blob/canary/packages/core/src/sheet.js LINE 36 and 38

A  code snippet to reproduce this, when accessed e.g. in Chrome via local file system access:

    <html>
      <body>
        <link href="./path-to/some.css" rel="stylesheet">
        <script src="./path-to/some-script-launching-stitches.js"></script>
      </body>
    </html>

## Concerns

While this might seem like a rare issue, I want to express some concerns about how this could affect special environments like e.g. hybrid apps on iOS relying on local access.

**UPDATE:** I can confirm that this issue affects iOS when using *WKWebView* with `loadFileURL`/`allowingReadAccessToURL` IF there's a local stylesheet linked.

## Expected behavior

Improved detection of `.cssRules` access rights.

## System information

- OS: macOS
- Chrome 
- Version of Stitches: 1.0.0

**Comment by sgrtho** [comment]
Is there a specific reason you're going through every stylesheet to find a hydratable one?

**Comment by jonathantneal** [comment]
Hey @sgrtho, we decided to use the CSSOM exclusively for hydrating stylesheets because it offered greater performance. However, `file:` & [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) restrictions may prevent us from reading CSS files, if they are created for Stitches.

The _easy_ solution would be to ignore all stylesheets with an href. However, we’ve always wanted Stitches to work if users were able to export their styles into a file. In other words, "inline stylesheets only" were never our end-game, which means the _easy_ solution would immediately break anyone exporting styles to files. However again, this would cause issues for anyone in `file:` or **CSP** environments. Another _easy_ solution would be not explicitly support `file:` or **CSP**. A less-performant solution would be to wrap each check in a try/catch block. However, we’d need to move all other logic out of the try/catch, lest we push it all into catchable memory.

The _right_ solution for all those scenarios would be to give hydration control to the user. This would require a new API. I’m in favor of it — since the brief existence of `insertionMethod` was quite popular — but it would require a lot more thinking.

**Comment by sgrtho** [comment]
Hi @jonathantneal, I don't fully understand what you mean by *if they are created for Stitches*... how do I create it *for Stitches*? :)

Nevertheless I need a workaround, which currently looks like that:

    <head>
      <style>
        --sxs { --sxs:0; }
        @media(sxs) { }
      </style>
      <link rel="stylesheet" href="styles/legacy.bundle.css"></link>
    </head>

Do you have other recommendations to make Stiches happy for now? According to...

https://developer.mozilla.org/en-US/docs/Web/API/Document/styleSheets

... the order should put `link` first, but that doesn't seem to be the case, because it works for me.

**Comment by jonathantneal** [comment]
>  I just edited this line ... to always be an empty list

If `sheets` is always an empty list, then Stitches cannot hydrate or make any runtime changes.

> it shouldn't be a problem if Stitches just manages their own `<style>` tag

That could be the way it works. However, it is currently possible to hydrate a `<link>` tag of Stitches styles, if they are written to a file instead of a `<style>`. It is also possible for Stitches to hydrate adopted stylesheets and constructible stylesheets, which would also not have any `<style>` tag.

> Is there any specific reason to iterate through every Stylesheet instead of creating one just for Stitches that I'm missing?

Besides the reasons mentioned above, by switching the lookup from stylesheets to document, this introduces new layers of fallback or complication for Node & Deno like setups.

> I didn't understand your response about file: & CSP

Browsers will disallow CSSOM access to certain kinds of styles, like those from other domains, those on the file system, and those protected by but not access-enabled by CSP.

**Comment by hadihallak** [comment]
Published under 1.2.6 🎉

**Comment by axelson** [comment]
Note: this bug also affects some extensions (such as Dark Mode on Firefox) that add stylesheets to loaded web pages.

Here's the full error to help in searching:
> Uncaught DOMException: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet
