### ISSUE TITLE
Margin/padding/etc won't merge if you use a variable

### ISSUE THREAD

**Issue by darklight9811** [modulz/stitches#791]
# Bug report

## Describe the bug

When using margin-left/right/top/bottom, they will merge if the value is the same, unless you use a variable.

## To Reproduce

https://codesandbox.io/s/admiring-water-kd0u1?file=/src/App.tsx

1. Create a theme and describe a variable
2. Create a component from it
3. Create a padding and a margin for all sides (left, right, top, bottom), one using a theme token, and the other not

## Expected behavior

If all the values are the same using a token, they should be merged

## Screenshots
![image](https://user-images.githubusercontent.com/20667774/133775655-0852ccec-2c2d-4181-9fb5-c5091d0947e2.png)

## System information

- OS: Windows 10
- Version of Stitches: 1.1.0
- Version of Node.js: v14.15.4

**Comment by jonathantneal** [comment]
Perhaps I am confused, but if you explicitly set all of them, I would expect that they should _not_ be merged. It sounds like unfortunate behavior by the browser’s older CSSOM technology, which happens to merge the values when they are not variables (_because they can’t necessarily guess the value of the variables, and because it was probably a bad idea to have ever collapsed them to begin with_).

**Comment by darklight9811** [comment]
@jonathantneal could you wait before closing, geez, that's why I left react. This behaviour does not happen with any other lib I tried, styled-components does not merge in any circunstance. And since I'm building every variant dinamically I needed that behaviour to work properly. So if this was not supposed to merge under any circunstance, that's still a bug to be fixed.

**Comment by jonathantneal** [comment]
@darklight9811, we can definitely still chat. Let me show you something.

Consider the following code. This is pure "vanilla" browser JavaScript. Mmmm. No libraries.

This is what happens when we run it in Safari:

```js
const { sheet } = document.head.appendChild(document.createElement('style'));

sheet.insertRule(`body {
	margin-top: 50px;
	margin-right: 50px;
	margin-bottom: 50px;
	margin-left: 50px;
}`, 0);

console.log(sheet.cssRules[0].cssText) // body { margin: 50px; }

sheet.insertRule(`body {
	margin-top: var(--50px);
	margin-right: var(--50px);
	margin-bottom: var(--50px);
	margin-left: var(--50px);
}`, 1);

console.log(sheet.cssRules[1].cssText) // body { margin: var(--50px); }
```

Did you see the same thing? If you did, you use Safari.

Chrome and Firefox will report the first `console.log` the same way. They will merge the `margin` declaration, which is what you expect. However, they will return something different than Safari for that second `console.log`. This is what they return:

```js
console.log(sheet.cssRules[1].cssText) // body { margin-top: var(--50px); margin-right: var(--50px); margin-bottom: var(--50px); margin-left: var(--50px); }
```

You have happened upon an example where Safari is the only _consistent_ browser. 😅

Personally, I wish the browsers wouldn’t collapse anything in either example. If I send them all 4, they should keep it that way. But that’s my own opinion.

Your bug report is that you expect things to work consistently, and that puts me in the uncomfortable position of telling you that the inconsistency is coming from Chrome and Firefox.

This isn’t coming from Stitches. We send the browser all 4 properties in both instances, whether it’s thru a pre-rendered `<style>` tag or a dynamic write to the CSSOM. It’s the browser that reports something different back to you.

I would agree this seems like a bug to be fixed. I’m going to send this to some friendly Chrome peeps.
