### ISSUE TITLE
Shorthand property parser

### ISSUE THREAD

**Issue by colmtuite** [modulz/stitches#81]
Currently, most shorthand properties just don't work, which is unacceptable.

Our options are:

1. Leave shorthand properties not working.
2. Build in specificity management which would give longhand properties precedence over shorthand properties, even when shorthand properties are declared below.
3. Write parsers to convert shorthand properties into longhand properties.

We're going with option 3. So we need to write parsers for at least the following properties:

- background
- margin
- padding
- border (Support for `none`)
- box-shadow (with tokens and chaining)
- transition (with tokens and chaining)
- animation
- border-radius
- font ??

**Comment by christianalfoni** [comment]
Okay, so I built this thing I think we can build on: https://codesandbox.io/s/css-property-parser-0o5nr?file=/src/index.js

I took the `background` property as it is one of the more complex.

It has two parts:

1. It parses a CSS prop value. This will be the same parser for any value. I think the only thing missing is handling quotes
2. The shorthand is expressed as a reducer, where it gets the tokens, the css object being produced and the value being processed. It also has access to the current position of the value and also the chain being handled. This will give any shorthand ability to control what it expects at different positions, if necessary

As you can see the example does a really complex background expression. I have yet to implement token lookup, but that is the easy part.

So yeah, will finish this and then try `font` as I believe that is the next level of complexity. After that it is a breeze.

To conclude I think this is absolutely doable and after a couple of more hours on this I think we should have something we can use 😄

**Comment by hadihallak** [comment]
Hey @christianalfoni 
I've already started working on shorthand when I did the animation PR
https://github.com/modulz/stitches/pull/88#issuecomment-673236490

is this something you plan to continue on doing? because this is something I was looking to continue working on next week so if you have this covered then I could look into something else.

**Comment by christianalfoni** [comment]
I am kinda ramming through every priority spewing out suggested implementations, so I will probably bump into work already done 😄 I do think I have found an API that allows us to implement any shorthand now, handling the complex parsing of the value needed, managing chaining etc. I want to try to see how the API fits in with the `font` shorthand, cause if that is pretty straight forward we have more than enough to handle the rest of the shorthands 😄 

So yeah, I will let you know here in the comments during the weekend with an example of the `font` shorthand using the same API and then I will have a final conclusion on suggesting it is a possible way to do it. 

But please play around with it and give any hints about it not working or you see some issues with the approach. Also if you see the approach of animations not having enough "umph" to handle things like background and font 😄

**Comment by hadihallak** [comment]
Awesome! good to know 😄 
I took a look and it looks good overall. however, I don't think that using regex and replacing as the main parsing function is reliable.

there are a lot of cases like slashed, functions with commas and quotes which makes parsing these values in this manner very unpredictable.
for example, if you do this `background: linear-gradient(red, yellow)` it will produce 
```
backgroundImage: "linear-gradient(red"
backgroundColor: "yellow)"
```

I think the best way to handle it would be a normal string-based parser. something similar to how other CSS parsers work.

**Comment by christianalfoni** [comment]
@hadihallak Yeah, I started out doing a string parser, but had an urge to push the regexping to see how far we could get 😄 

Btw... I don't know if @peduarte got a chance to mention to you yet. The way I do things now is that I implement everything in `pocs` as "code to reference". I think it is much better that you merge in what you have done in the PRs, as taking the ownership in the code is number 1 priority and you cleaned it up really nicely!

Then after I have rushed through everything, also taking into account all your great feedback, I will give you an overview of the implementations I have done. Then you can decide what parts you want to include and how you want to include it in the actual codebase. Cause then you have ownership in that as well 😄 

If we get short on time we can rather do a review of the suggested changes and I can rather split them up into separate PRs 😄 

Let me play some more with this, looking into parser as well as `font` and `animation` as those two are heavy duty shorthands 😄

**Comment by christianalfoni** [comment]
Okay, got an updated sandbox now: https://codesandbox.io/s/css-property-parser-0o5nr?file=/src/index.js

still running regexps, but it handles "commas in parenthesis" and "spaces in quotes"... it is just less lines of code and more approachable I think. GIVEN that it actually works 😂 

Also added animation. With this API it took me 15min implement parsing of animation... again GIVEN that it works 😂 

Will try `font` when I got a change. But I like this "reducer" like approach as it seems to give the flexibility needed. Let me know if you find any vulnerable spots in the initial parsing or the reducing of the values 😄

**Comment by christianalfoni** [comment]
Okay, got `font` in there now as well. Trying out `transition` now 😄

**Comment by christianalfoni** [comment]
Oh, wow... nice, that went fast (same sandbox). `box-shadow` up next 😄

**Comment by christianalfoni** [comment]
`border` is in, and also `borderWidth`, `borderStyle` and `borderColor` as those also are shorthands

**Comment by christianalfoni** [comment]
Okay, also got `borderRadius` in there, though I dropped the elliptical thing for now... no problem to introduce it, but requires quite a bit of extra code in the "reducer". Have not added token evaluation there yet, but little code to do that.

This in total adds about 1.5kb (gzip) to the payload of stitches. So still way below the others.

So yeah, let me know how far we should take this and I will introduce tokens in the meantime 😄

**Comment by peduarte** [comment]
@christianalfoni nice, thanks for the updates! Let me know when they're in stitches and I'll do some tests

**Comment by christianalfoni** [comment]
@peduarte Will try to get it in this evening, but would encourage to just play around with the Sandbox... see if you can create unexpected outputs 😄 

https://codesandbox.io/s/css-property-parser-0o5nr?file=/src/index.js

**Comment by peduarte** [comment]
Cool, will do!

**Comment by peduarte** [comment]
>  It turns out box-shadow is not really a shorthand. It does not map to any other lower level CSS properties, so no reason to parse it 😄

@christianalfoni  haha yep, no long hands for box-shadow (unfortunately) 😄 

to clarify though, we'd still need to parse tokens there 👍

**Comment by christianalfoni** [comment]
Yeah, though since there are no longhands for box-shadow, there is no way to get into specificity issues either :) But yeah, we can still introduce it as a "fake shorthand", hehe... basically to do the parsing. But it produces a normal `boxShadow`.

Jup, sandbox includes lower level shorthands for border as well... oh, but they also have for specific sides? 😂  Those did not pop up on `MDN`, but anyways, no problem to support that.

**Comment by hadihallak** [comment]
@christianalfoni  you're wild with Regex. Respect 😄 
Love how clean the parsers are and overall they seem to be performing very well in terms of speed.

I did some quick tests and it looks like they work well apart from the initial value parser. currently, it fails with nested CSS functions for things like `linear-gradient( red, hsla(120,100%,50%,0.3))` so I'm still leaning towards a string-based parser especially since we are likely to need one when we work on vscode extensions for linting and IntelliSense

let me know when this is ready and I will migrate it over and write tests for it.

**Comment by christianalfoni** [comment]
Ah, there you go, nesting 😂 

Ah well, maybe that is a really good separation then. I think you'll write a much better string parser than me, and then my contribution is the "reducer" thingy 😄 

I believe it is ready now. I did a couple of small changes:

- Now the "tokens" are passed in with the value. That means all the "propertyParsers" can be built ahead of time and then the tokens and value is passed in when it actually runs
- Since the actual token categories are a bit in flux I have not taken into account everything, but you see how I approach it and later changes should be easy to fix
- It requires that all token categories are defined, to avoid unnecessary lookups... thinking this is okay. So when stitches fires up it fills in missing token categories with empty objects
- I also add `boxShadow` as we want to parse that regarding tokens

Okay, go get it: https://codesandbox.io/s/css-property-parser-0o5nr?file=/src/index.js 😄 

Let me know if you have any questions or need help with anything. I will just continue going through the next set of priorities with suggestions on how to implement 😄

**Comment by hadihallak** [comment]
Initial parsers are added in #105
