### ISSUE TITLE
Media queries inside variants

### ISSUE THREAD

**Issue by colmtuite** [modulz/stitches#86]
We need to be able to place media queries inside a variant block.

```
.Button.blue {
  @media (hover: hover) {
    // cool hover effect for the blue variant
  }
}
```

This is possible in all popular css-in-js libs and preprocessors.

Without it, styling components becomes unmaintainable.

This may be related to #79.

**Comment by peduarte** [comment]
Yep, definitely 💯 

Here's a Codesandbox with a repro: https://codesandbox.io/s/stitches-media-query-in-variant-sd93t?file=/src/App.tsx

As a rule of thumb: anything that can be done in the base styles, should be supported in variants

/cc @christianalfoni just wondering if you had ever come across this and if it was intentional? (the error message is funny!)

**Comment by hadihallak** [comment]
@peduarte been looking into supporting inline media queries today and @christianalfoni keep me honest but I think this might be intentional because currently, we don't support nesting screens and because variants get converted to responsive ones that map to your screens when you do a screen inside a variant you're practically nesting the screen in all other defined screens which is disallowed intentionally for reasons @christianalfoni  mentioned here https://github.com/modulz/stitches/issues/67#issuecomment-671025206

Still looking into this but overall, I'm in agreeance with @christianalfoni on the whole nesting media queries thing, as it's not only very tricky but, might be near-impossible to solve gracefully.

**Comment by hadihallak** [comment]
so looks like Otion did the sorting thing to get around the specificity issues which appear to be working well from my initial testing so will give this another spin tomorrow and see how it goes

**Comment by peduarte** [comment]
@hadihallak yeah I fully understand the complexity here 😕 

Personally, I'd be totally fine with not supporting media queries within the Variant Style object, and instead, force people to change their variants responsively at the consumption layer. But Im not sure everyone is ready to think this way yet...

Hmm, is there a way to know that, if a variant contains responsive styles, and the user users the responsive syntax to apply that variant, we throw a warning? (or ignore one of the media queries)? Just throwing an idea out there :D

**Comment by colmtuite** [comment]
The issue with this one is not about breakpoints. With breakpoints, it's fine to just define your variants and then apply them at consumption.

This issue is about all of the other media queries which are not breakpoints. Like `@hover: hover`, for example, which should be applied every single time you define a hover pseudo class. Or `(prefers-reduced-motion)`, or any of the others.

The lack of support for nested media queries makes building high-quality component libraries unmanageable. It's not something we can prevent or ignore. If we can't solve very soon, we'll have to switch back to Stylix.

**Comment by peduarte** [comment]
Yep. We should allow nested `mediaQueries` 👍 

To clarify, we need it to work like this:

```js
styled('button', {}, {
  variant: {
    blue: {
      backgroundColor: 'royalblue',
      '@media (hover: hover)': {
        ':hover': {
          backgroundColor: 'navy'
        }
      }
    },
})
```

This usage:
```jsx
<Button variant="blue">Blue button</Button>
```

Should write this css:
```css
.bg-200 {
  background-color: royalblue;
}

@media (hover: hover) {
  .hover-bg-400:hover {
    background-color: navy;
  }
}
```

If the variant is applied within a media query:
```jsx
<Button variant={{ '@media (min-width:480)': 'blue'  }}>Responsive button</Button>
```

Then it should write this css:
```css
@media (min-width:480px) {
  .md-bg-200 {
    background-color: royalblue;
  }
}

@media (min-width:480px) {
  @media (hover: hover) {
    .md-hover-bg-400:hover {
     background-color: red
    }
  }  
}
```


Does this look right to everyone?

**Comment by colmtuite** [comment]
Looks perfect. Thanks for demonstrating all that 💯

**Comment by christianalfoni** [comment]
Okay, so I am running a branch on `poc` where I have implemented media queries.

The way it works is that the atom now has a notion of `mediaQueries`, which is identified by looking at `@` at the beginning of a selector. When the CSS rule is created it iterates the mediaQueries to create nested rules, where the actual CSS rule is inside the very nested media query.

To handle specificity issues every nested level adds an additional classname to the rule  (`.c0.c0`), increasing specificity. That means you can feel safe when writing media queries that order of injection does no matter. This is not all an "atom approach" issue, more the fact that media queries does not add any specificity to a rule, so generally weird things can happen. So we are basically making it even more predictable than it really is 😄 

I am not writing tests, just ensuring that I do not break any existing tests. So please try it out on `poc` branch.

**Comment by peduarte** [comment]
@christianalfoni sounds great, thanks for the update!

**Comment by hadihallak** [comment]
@christianalfoni I think we might be referencing two different issues then. Apologies for the mix up.

 I’ve created a codesandbox that uses your poc version of stitches to showcase how it will produce un-expected results just by changing the rendering order of components (hence the injection order of atoms).
https://codesandbox.io/s/affectionate-meadow-rhzbd?file=/src/App.js

**here is a video of how this might occur:**
https://drive.google.com/file/d/1eTpEmy12aydZd4xYjPHlZLj9-Fuw-AkA/view?usp=sharing

**Comment by christianalfoni** [comment]
Thanks a bunch for testing that @hadihallak ! Yeah, hm, this really shows that media queries can not be "atomized". Or, if they are going to be atomized we need to parse them and understand their order based on how they are expressed. Like check for `min-width`, `max-width` and their values etc. But that is pretty intense.

So there is a simple solution here and that is to make all media query atoms unique. It basically just means that stitches can not re-use the media query atoms, unless you express them in the `mediaQueries` config, which really is intended for recurring media queries. 

Lets have that as a fallback, while we think a bit more 😄

**Comment by christianalfoni** [comment]
Oh, I have an idea... now we are increasing specificity by nested media queries... we can also increase them on the same level. Which means:

```ts
{
  "@media screen and (min-width: 200px) ": {
    backgroundColor: "green"
  },
  // This will get higher specificity because you have defined it as the second one
  "@media screen and (min-width: 300px) ": {
    backgroundColor: "yellow"
  }
}
```

Doing this specificity increase does help the mental model of dealing with media queries, as they will run as you define them.

Here is updated sandbox @hadihallak : https://codesandbox.io/s/tender-sun-gu4s3?file=/src/App.js

**Comment by christianalfoni** [comment]
Oh, I have an idea... now we are increasing specificity by nested media queries... we can also increase them on the same level. Which means:

```ts
{
  "@media screen and (min-width: 200px) ": {
    backgroundColor: "green"
  },
  // This will get higher specificity because you have defined it as the second one
  "@media screen and (min-width: 300px) ": {
    backgroundColor: "yellow"
  }
}
```

Doing this specificity increase does help the mental model of dealing with media queries, as they will run as you define them.

Here is updated sandbox @hadihallak : https://codesandbox.io/s/tender-sun-gu4s3?file=/src/App.js

**Comment by hadihallak** [comment]
@christianalfoni I kinda landed on the same conclusions. here are my thoughts:
- processing media queries is a bit heavy for the task and we might need to make hard decisions when we encounter things mixed queries or @supports or @hover media query because these aren't sortable 
- creating atoms might be the most bulletproof solution but might end up causing the generation of a lot of new atoms that could've been re-used in a perfect world with no CSS issues (like if we support nested screens or for things like variants)

the specificity idea is very interesting. will give it a try and let you  know how it goes but I'm suspecting it might not be as bulletproof as doing inline atoms

**Comment by hadihallak** [comment]
this feels a lot better already 💯  but there are cases where this might produce the same results although with not a very unusual usage https://codesandbox.io/s/elated-sea-7rqij?file=/src/App.js

**Comment by christianalfoni** [comment]
@hadihallak I guess `@supports` is also considered a `mediaQuery`? Or is that something else? Cause now I explicitly check for `@media`, but can just add `@supports` to that match 😄

**Comment by christianalfoni** [comment]
https://github.com/modulz/stitches/commit/0f63cdd4ef2c16597c34d6beb98f62b6511a7622

I now do a check for `@` at the beginning of selector, instead of `@media` explicitly. So `@supports` is covered by the same logic.

**Comment by hadihallak** [comment]
My head is getting fried from thinking of all of the cases in the large scheme of things so I'm not much use for now 😄 
I think we're getting there tho. Thanks for looking into this very quickly. I think we will concur this with some more testing back and forth 💪

**Comment by peduarte** [comment]
@chancestrickland @hadihallak I couldn't get responsive variants to work anymore in the `pocs` branch, so I checked the source of `styled` package, and I think we're still relying on the `screens` key:

Checkout this line https://github.com/modulz/stitches/blob/pocs/packages/styled/src/index.tsx#L407

I replaced it with `const configScreens = (css as any)._config().mediaQueries;` and it works

Thought I'd let you know

**Comment by christianalfoni** [comment]
Oh, ops, fixed 😄

**Comment by hadihallak** [comment]
@christianalfoni first off, it's crazy you came up with the specificity implementation in what feels like 30 mins. really impressive 🎩 

**Here are my two cents after trying it and trying to break it 😄 :**
- I couldn't replicate the issue I referenced in the video above 💯 
- Was really nice that this solution tries to minimize the generation of unique atmos
- increasing specificity implicitly made maintaining styles/variants/overrides a very tiresome and prone to error task once inline media queries are involved. add one media query somewhere and you might break everything. or you would need to manually add specificity to your overrides for them to work correctly (see: https://github.com/modulz/stitches/issues/97)

**I suggest is that we stick with this:**
> So there is a simple solution here and that is to make all media query atoms unique. It basically just means that stitches can not re-use the media query atoms unless you express them in the mediaQueries config, which really is intended for recurring media queries.

- we advertise that abstracted mediaQueries are the right way of doing things
- generate complete unique atmos whenever inline media queries are involved. this way we don't have all of the specificity related issues that come from trying to minimize the creation of unique atmos
- heavily document that inline media queries should be treated as an escape hatch and that they hurt style re-usability.

I think what you did when you introduced screen (abstracted media queries) is very powerful and predictable at the same time so we can show people how to nest media queries there like this:
```js
const { styled } = createStyled({
  mediaQueries: {
    myNestedQuery: (rule) =>
      `@media(min-width:300px){ @media (hover: hover) {${rule}} }`,
  }
});
```

this syntax is already supported in all major browsers without any CSS preprocessor so I think we should be fine if we advertise it as the way to do things.

Personally, I don't think that messing with specificity is the right way to go and would suggest that we keep things simple like what you mentioned in the comment above and rely on abstracted media queries as much as possible.

Keen to know what everyone thinks.

**Comment by christianalfoni** [comment]
@hadihallak This is just amazeballs testing and I think you conclusion makes sense. Using specificity to handle this will not work. I did go through your examples and fixed a bug you found related to selectors in general. I also removed the specificity stuff for media queries: https://codesandbox.io/s/bugs-test-cases-forked-33o7h?file=/src/css/index.ts

I want to give it a little bit more thought until we give in to the fallback, but for me personally your reasoning makes a lot of sense. Cause I would argue that having a bunch of random media queries all over would create a very unpredictable design? They are more exceptions than the rule? Just like `css` prop is an exception, not how you design your app?

Anyways, will get back to you on this one 😄 

Thanks again for excellent examples making it very easy for me to trigger new thoughts and fixing issues!

**Comment by christianalfoni** [comment]
Okay, so I have made up some thoughts today:

Even when making each inline media query unique we have a challenge. This uniqueness needs to be based on something, which is not a problem for the client. But it is a problem for server side rendering. Typically we would just use a sequence, or some random thing, to produce the classname. But neither creates consistency across client/server. So we actually have to deal with this somehow.

I see two different ways of dealing with this:

1. We do a conceptual change. Instead of having `mediaQueries` as a config, we call it `breakpoints`. Cause media queries is not the problem, it is the breakpoints that is messy related to specificity. So the API could then be:

```ts
{
  tokens,
  breakpoints: {
    mobile: { minWidth: '600px' },
    tablet: { minWidth: '1000px' }
  }
}
```

These breakpoints are converted into media queries, but conceptually they deal with breakpoints in the app. All other kinds of media queries are done inline as normal. So would have to document that inline media query breakpoints does not ensure specificity. 

2. We deal with `width` and `height` (with their respective min and max). The way this would work is that all media queries are parsed and we look at what breakpoints they represent. By tracking what breakpoints has been inserted we are able to figure out at what position the CSS rule should be inserted using `addRule` instead of `insertRule`. There is a parsing library already, https://github.com/ericf/css-mediaquery, but we do not need all the parsing. Only need what affects breakpoints.

Option 2 would be the most elegant as it would not matter what order you insert your `mediaQueries` in any situation. They are always inserted at the correct point in the stylesheet based on what they actually try to express.

I am going to play around with 2, but let me know what your thoughts are 😄

**Comment by christianalfoni** [comment]
Okay, still leaning on `breakpoints` being the best solution (because it explicitly defines what breakpoints your app operates with), we could make atoms representing media queries a `MediaQueryAtom`. What is special about these atoms is that they are treated differently in the composition. Btw, the composition is what goes through the array of atoms and figures out which one should be part of it and then `toString` them to produce the whole classname string 😄  :

- The composition iterates a `MediaQueryAtom`
- The composition creates a hash based on all the atoms being part of the composition
- The `MediaQueryAtom` is now updated with this "composition-hash"
- When the className is now created for the `MediaQueryAtom` it will include the "composition-hash"

This will work consistently between client and server. Now... we really only need this behaviour for "media query breakpoints", so we could rather name is `BreakpointAtom` with the same behaviour.

So yeah... either using `breakpoints` as a configuration and that is where breakpoint specificity is handled. Or I can explore the approach described here 😄

**Comment by hadihallak** [comment]
@christianalfoni Thanks a lot for doing this detailed research 🙏  
I will be thinking more about this today and help with the research as specificity issues have been the most tricky thing to deal with so I think it's good if we spend some time on this making sure that we tick all the boxes so here is my initial feedback:

Personally I like the breakpoints approach a lot. this is how we currently handle breakpoints in Radix and it has been working nicely.

> I also thought about parsing the media query to figure out the breakpoints, but I see now that is also impossible, because you can have things like (min-width: 400px, max-width: 40rem)

Great point 👍 

> So would have to document that inline media query breakpoints does not ensure specificity.

Do you mean the specificity related to injection order or something else?

> When the className is now created for the MediaQueryAtom it will include the "composition-hash"

so the classname for each MediaQueryAtom/BreakpointAtom would be something like this `.hash.atom-class`? and if this is the case, does this mean that we will be generating new atoms whenever the composition changes (variants + css prop) to guarantee that we won't have injection order related issues with media queries

**Comment by christianalfoni** [comment]
> Do you mean the specificity related to injection order or something else?

Ah, yes. Basically if you do like a `{ '@media (min-width: 200px)': { color: 'red' } }` we can not ensure it will work if you use that media query inline somewhere else as well.... hm... that makes me think that we can actually keep a reference to all media queries and if duplicate media queries containing breakpoints occur we can show a warning saying. "You have the same media query breakpoints in different compositions, please define this as a breakpoint in the configuration instead to ensure specificity".

> so the classname for each MediaQueryAtom/BreakpointAtom would be something like this .hash.atom-class

Jup, exactly. So basically each composition using the atom would "clone" the atom using the hash of the composition itself. So basically inline media queries would not be reusable. But yeah... with even having a warning as explained above I lean even more over to breakpoints config.

> Since we are creating responsive variants that map to each breakpoint, what would happen when you nest a breakPoint inside a variant?

Good question 😄  So the inline media queries should be nested inside the breakpoints configured. Meaning if you do:

```ts
<Button someVariant={{ mobile: 'someVariantValue' }} />
```

If `someVariantvalue` has a nested media query, that will just be injected inside the `mobile`:

```ts
@media (min-width: 640px) {
  @media (min-width: 700px) {
    .someVariantValue {}
  }
}
```

Btw, I thought I would rather go ahead now and create PRs based on the stuff we have already concluded on. So get ampersand support and the bug fixes in etc. So I will not do anything more with `pocs` now, but rather help getting these things into `master` 😄

**Comment by hadihallak** [comment]
@christianalfoni  great insight as always 💯 

so I just had a chat with @colmtuite and we're leaning towards keeping`mediaQueries` because `breakpoints` discourage you from abstracting other media queries.
we also discussed the possibility of having both `breakpoints` and `mediaQueries` at the same time but this isn't ideal as they're practically the same thing.
I also chatted with @peduarte and he also likes the flexibility of `mediaQueries`

**So pretty much what we're thinking of is that:**
- we do a similar implementation as the latest one you suggested but we would prefer to have `mediaQueries` instead of breakpoints (maybe we could separate them internally by doing some regex matching)
- when inline media queries are involved (the ones that have breakpoint related issues) we want to try to ideally eliminate specificity issues by treating these atoms as breakpoints atoms as well and giving them the hash treatment.
- Document best practices to teach people to avoid using inline media queries (the ones that have breakpoint related issues). maybe we could throw the warnings you mentioned while also providing them with a link to the best practices page

so ideally, what we're trying to do is that even if someone used inline media queries, we'd prefer that the library handles this situation in the most optimal way possible to user expectation while also providing the user with some useful info on un-optimized media usage and how he could fix this.

What do you think of the above? do you foresee any difficulties if we go with it?

**Comment by christianalfoni** [comment]
Thanks for the summary! 😄 

So one final argument to make sure we are not doing any unnecessary implementation. If we want developers to use the `mediaQueries` configuration and we want to warn them when using inline breakpoints, is the composition hash worth it? Cause especially with a warning I would suggest developers wants to remove it? Meaning that when they write an inline media breakpoint and sees the warning... they will immediately fix it?

It will take some time finding a good way to handle the composition hash, cause it fundamentally contradicts the isolated atomic approach. So need to find a way that does not affect performance for all the other normal atoms 😄 

Just taking on the role of "the protector of the code" to make sure we are completely certain 😂  Will not push back anymore if we still want to move on with the composition-hash, like... it is a fun thing to work on, but yeah, just have to be absolutely sure it is worth it 😄

**Comment by hadihallak** [comment]
> So one final argument to make sure we are not doing any unnecessary implementation. If we want developers to use the mediaQueries configuration and we want to warn them when using inline breakpoints, is the composition hash worth it? Cause especially with a warning I would suggest developers wants to remove it? Meaning that when they write an inline media breakpoint and sees the warning... they will immediately fix it?

I would hope that this would be the case. for me it goes like this:
1. We're confident enough that inline media queries aren't going to be used and in this case, the library should throw an Error whenever we detect someone is nesting media queries or at the very least give clear warnings that we can't guarantee the specificity of inline media queries and that they might and might not work now or in the future due to injection order and then it would be up to the dev to take the risk or not. maybe we could have a mode `__UNSAFE__ENABLE__INLINE__MEDIA__QUERIES` in the config.
2. We think there are uses for when people might need inline media queries and then for me at least, I think we should guarantee that it's gonna work regardless of the injection order.

So if we are confident that there are no uses for inline media queries then I'd say by all means we should remove them and save ourselves the implementation headache.

cc @colmtuite @peduarte

**I have a few questions tho if we go this route of disallowing inline media queries:**
1. will it be allowed to nest `mediaQueries` inside each other?
2. and if the answer is no to the above then how would we handle `mediaQueries` in responsive variants (as they already get wrapped by `mediaQueries` themselves so wouldn't this be kinda like inline and prone to the same issues under the right circumstances as well?


> It will take some time finding a good way to handle the composition hash

I think we could take the approach of converting the css definition to string then hashing it into a css class which is something similar to the way other css-in-js libraries handle it

>  it fundamentally contradicts the isolated atomic approach

Totally agree. and honestly, if it were to me I would go with something similar the prototype @jjenzz  did without nesting and with everything done using js states and all but I think we got caught with a mix of requirements that fundamentally contradicts with each other and now every fix seems like a hack.

> Just taking on the role of "the protector of the code" to make sure we are completely certain 😂 Will not push back anymore if we still want to move on with the composition-hash, like... it is a fun thing to work on, but yeah, just have to be absolutely sure it is worth it 😄

this discussion is very good. This is a big change and I think we should all be aligned on the expected outcome. so please keep the feedback going.

So if we're voting I'd vote to remove inline media queries completely if we're sure that there are no valid use-cases for it or just hide it under a flag. otherwise, we should support it.

**Comment by jjenzz** [comment]
It seems there are valid use-cases for inline media queries when a particular media query is used once or when prototyping. Correct me if I'm wrong @christianalfoni, but I think the suggestion is to have a warning only when the same media query appears inline **more than once** to guide them towards abstracting it into the config.

That approach would mean that users will likely abstract to prevent specificity issues and there is no need for us to implement something to prevent issues. They can still define duplicated inline media queries at their own risk.

Sounds like the simplest approach to me if I've understood correctly 🙂

**Comment by colmtuite** [comment]
> will it be allowed to nest mediaQueries inside each other?

I don't see how one issue is related to the other? Whether I'm using `mediaQueries` or inline media queries, I'd want to nest them. Disallowing inline media queries is unrelated imo.

```
hover: {
  motion: {
    // styles only applied if prefers-reduced-motion and hover input device
  }
}
```

Maybe we could automatically unwrap this and combine them using the `and` operator? Or maybe we could decide to force to user to set-up a single media query which includes both.

But imo, the path of least resistance for the user is to just allow this.

**Comment by christianalfoni** [comment]
Exactly @jjenzz 😄  The warning would only appear when we see TWO different compositions which has the exact same media query with the same breakpoints in them. So you can still inline as normal, prototype etc. ... only when we actually see a possible issue the developer is warned about it 👍

**Comment by christianalfoni** [comment]
@colmtuite Ah, yes, there is some history here. Initially the screens represented breakpoints, so was only intended for breakpoint types of media queries. And did not make any sense to say like: `{ MOBILE: { DESKTOP: { color: 'red' } }`. But it being a general media query thing, I totally see the argument 👍 

Currently a mediaQuery at the configuration level means "Create a new style tag for this stuff". It basically just creates a "bucket" for where we can insert CSS rules at any order, grouped inside a breakpoint. 

So yeah, we would need to change the approach if `mediaQueries` is going to be any mediaQuery. Sorry, I should have picked up on that earlier. Hm... This is really interesting. Because technically a `breakpoint` is something very different than a media query, though conceptually for a user a "media query is a media query". 

So okay, to summarize again. To use the current "bucket" approach to deal with breakpoint specificity it would be ideal if we did a config of:

```ts
{
  tokens: {},
  breakpoints: {
    mobile: '500px'
  }
}
```

So user do not use other media queries there. Then they are allowed to use any kind of media query inline:

```ts
{
  '@media (hover)': {
    '@meida (motion)': {
      ...
    }
  }
}
```

They can also use inline media queries with breakpoints, even nested:

```ts
{
  '@media (min-width: 300px)': {
    '@media (min-width: 400px)': {}
  }
}
```

But if they were to write two inline media queries with breakpoints that are exactly the same:

```ts

```ts
const a = css({
  '@media (min-width: 300px)': {
    '@media (min-width: 400px)': { color: 'blue' }
  }
})

const b = css({
  '@media (min-width: 300px)': {
    '@media (min-width: 400px)': { color: 'red'}
  }
})
```

We would say: "WARN - The property "color" with media query bla bla bla can cause a specificity issue. You should create a breakpoint".

Something like that... least resistance technically, and conceptually separates the "bucketing requirement" of breakpoints and the nesting you want with all other media queries.

Hope I explained that okay. I can summarize better later, kindergarten pickup 😄

**Comment by hadihallak** [comment]
so I very much like this.  this would mean that we don't have to generate any atoms while also providing the users with warnings only when things could go wrong instead of just disabling the whole thing.

At first, I thought we'd need to normalize the selectors (for when two different selector strings are different but mean the same thing in css) but I think and correct me if I'm wrong with the assumption but even if we don't normalize the selectors. the worst thing that could happen is that we'd create new atoms which is totally fine because ultimately what we're trying to avoid is to have two responsive inline atoms spread across two different components and from the looks of it, this solution should be sufficient.

Amazing job man! really love this 💯

**Comment by christianalfoni** [comment]
Yes, exactly @hadihallak, the resulting CSS class would get a different `id` because the selector is different 😄 

And also, just to be clear... you can still do:

```ts
{
  tablet: {
    '@media (hover: hover)': {
      color: 'red'
    }
  }
}
```

It is just this inserting a breakpoint inside a breakpoint that breaks the concept. `{ someDefinedMediaQuery: { someOtherDefinedMediaQuery: {} }`.

You can also do:

```ts
{
  tokens: {},
  breakpoints: {
    complexBreakPoint: css => `@media (min-device-width: 300px) { @media (min-width: 400px) { ${css} } }`
  }
}
```

And then use that with any CSS rules: 

```ts
{
  complexBreakPoint: {
    color: 'red'
  }
}
```

The `breakpoints` config just puts the exact specificity order in the hands of the developer. Which is why the breakpoints themselves  not be nested, because then we would end up in specificity issues again 😄 

You break a sweat just talking about this stuff 😂

**Comment by hadihallak** [comment]
we can do this via utils so I'm going to close this as #112 is merged in
