### ISSUE TITLE
Global styles don't clear when component gets unmounted

### ISSUE THREAD

**Issue by julianbenegas** [modulz/stitches#884]
# Bug report

## Describe the bug

`globalCss` that's applied in a component (in this case a Next.js page), does not get unmounted (removed from the stylesheet) when the component gets unmounted.

## To Reproduce

1. Go to [this StackBlitz](https://stackblitz.com/edit/nextjs-mp1qha?file=pages/index.js).
2. Navigate through pages to see how global styles applied in `/test` affect the contents of `/`.

## Expected behavior

In my opinion, global styles should be cleared with the component.

## System information

- OS: macOS
- Version of Stitches: 1.2.5
- Version of Node.js: 14.16.0

**Comment by peduarte** [comment]
Yeah, that's by design. Out of curiosity, why would you want to clear global styles? Stitches does offer a `reset` function if you really need, it's used internally mainly, but if you really need to you can use it. Cc'ing @hadihallak to ensure I'm sane

**Comment by julianbenegas** [comment]
Ah, I understand. I'm using it for some layout stuff. Basically, we're building a site which has a shared layout, but one page needs to hide a part of that shared layout. It can be done other ways, but still I in my opinion, global styles should unmount with the component. In fact, global styles get mounted with the component — they are not on the stylesheet until the component gets mounted — so in my mind, it makes sense that they unmount with the component.

> but if you really need to you can use it
No worries, I solved the specific issue by using `<style jsx global></style>`, which works the way I'm describing!

**Comment by hadihallak** [comment]
Styles never unmount and that's by design as Pedro mentioned.
The reset functionality will only reset the internal representation of the sheet so it will not remove the styles once they are inserted.

**Comment by Clee681** [comment]
FWIW, I hit the same issue as @julianbenegas and also resorted to `<style jsx global></style>` since I'm using Next.js

The scenario was we conditionally mount a `VideoPlayer` component which when viewed on mobile in landscape orientation shows ugly white bars on the left and right side on iPhones. This is because the viewport is within the "safe area". One option to make this look better is to conditionally set the `body` `backgroundColor` to be black only when the `VideoPlayer` component is mounted.
